version: '3'

services:
  web:
    image: 'alpine/git'
    restart: always
    hostname: 'localhost'
    ulimits:
      core: 0
      sigpending: 62793
      nproc: 131072
      nofile:
        soft: 60000
        hard: 60000
    privileged: true
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'https://localhost'
    ports:
      - '81:80'
      - '443:443'
      - '22:22'
    volumes:
      - gitvol:/root
 #     - gitvol:/var/log/gitlab
 #     - gitvol:/var/opt/gitlab
volumes:
  gitlabvol:
    external: true