#docker volume create --name gogs-data
#docker volume inspect gogs-data

#docker run --name=gogs -p 10022:22 -p 10080:3000 -v gogs-data:/data gogs/gogs

version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: 'gogs/gogs'
    restart: always
    hostname: 'localhost'
    ports:
      - '10022:22'
      - '10080:3000'
    volumes:
      - gogs-data:/data:rw
volumes:
  gogs-data:
    external: true